### ISSUE TITLE
Manually creating user

### ISSUE THREAD

**Issue by condolent** [panique/php-login-minimal#30]
Hello, liking this alot!

Is it possible to manually create users? I just don't know how to generate a password hash to store in the DB.

~~Also another question; how can I add more pages that you need to be logged in to see?~~ <- figured that one out

**Comment by panique** [comment]
Hi, sure, you can just use http://php.net/manual/de/function.password-hash.php for that

**Comment by condolent** [comment]
Ok thanks, is this script using password default hash thing, like in that manual? In that case; this code should work right?
``
echo password_hash("rasmuslerdorf", PASSWORD_DEFAULT)."\n";
``

**Comment by panique** [comment]
dude have a look at the code, seriously! or read the readme! why do you take the time to write such a ticket when you could find this out by yourself in 3seconds ?

**Comment by condolent** [comment]
The fuck? Just wondering what sort of hash your script is using. No need to be an asshole.

You've created a script to help people out and when they ask a question about it you just answer like a inbred cuck. You're messed up

**Comment by panique** [comment]
Nono, it's just crazy how people write support tickets but are not able to have a simple look on their own, read the readme or simply use the search function like everybody else. This is not arrogant... What exactly do you expect ? You have asked 3 questions that show you absolutly not even looked in the code or the readme or not even tried anything on your own. You can find it out within 3seconds. I find it extremely annoying to work on software like this for 100s of hours, write large readmes, tutorials and video guidelines and explaining in detail how to add a page and then people write support ticket saying "please tell me how to add a page". so, please look into the code, Read The Manual by yourself or use the search function, it's so easy.

**Comment by condolent** [comment]
rofl, nice dude. I removed the "how to add a page" the second I added it because I read the readme and found out how. Great job man! You're an asshole, giving out free scripts and when people ask for help you're being rude, making a great picture of yourself man! Keep it up!

I've asked question nicely and you reply with such a rude response it's retarded. Once again; you're messed up. It's a simple yes or no question I asked and you'd rather take the time to write a long shitpost about how I can find it on my own very easy. Bet you have alot of friends with this attitude. Peace out, girlscout

**Comment by panique** [comment]
Ok, I am an asshole because i spend 1000s of hours writing free software that you can use to build your company and earn a lot of money, and because i spend 100s of hours commenting every line, writing huge tutorials, huge readmes and even giving free support for REAL problems, but then don't want to spend even more time googling your problem for you ? I have answered 1000s of tickets in the last 7 years, and i do this unpaid in my free time. So what the hell do you want ? What are you doing for free for others ? Grow up and get a life!

Beside that, i have not even said anything rude to you. I think you should just be able to read a readme or do a search on your own, pasting "password_hash" into the above search box or into your IDE costs you 3secs. You have not even tried to solve your own problem. People like you are why the world is broken. You get everything for free and then still complain.

**Comment by panique** [comment]
Ok, I am an asshole because i spend 1000s of hours writing free software that you can use to build your company and earn a lot of money, and because i spend 100s of hours commenting every line, writing huge tutorials, huge readmes and even giving free support for REAL problems, but then don't want to spend even more time googling your problem for you ? I have answered 1000s of tickets in the last 7 years, and i do this unpaid in my free time. So what the hell do you want ? What are you doing for free for others ? Grow up and get a life!

Beside that, i have not even said anything rude to you. I think you should just be able to read a readme or do a search on your own, pasting "password_hash" into the above search box or into your IDE costs you 3secs. You have not even tried to solve your own problem. You get everything for free and then still complain.

**Comment by condolent** [comment]
Your arrogance is hillarious, honestly!

**Comment by panique** [comment]
No dude, your lazyness and self-evidence! Coming to this project, 3 years after it's closed, asking weird lazy questions, getting answers and still complaining and calling me "asshole". Seriously, get lost or you you'll get stress with GitHub abuse team.

**Comment by k0nsl** [comment]
@condolent: Haha! Du kallade honom for en "cuck", men det låter mer som om du själv är en "cuck".
